### PR TITLE
+Windows x64 binaries

### PR DESCRIPTION
**Pull request by zx70**
This is built basing on my recent fork (https://github.com/CodeAsm/M2000/pull/2) to the @CodeAsm emulator's adjustments.

### CODE REVIEW

**Comment by zx70** [comment]
@CodeAsm, I opened a pull request, will you merge the code ?

**Comment by CodeAsm** [comment]
This is @dionoid repo, I cant.
But ill look at your pull request real soon. never had thought about what to do with requests like this.
looks fine sofar :smile:

**Comment by zx70** [comment]
I guessed so.  GitHub works beautifully in building chains of contributions, no mattere whether you are ready or not  :D

**Comment by dionoid** [comment]
Good to have a win64 version of m2000.exe, but it looks like these binaries weren't built using the source code in emulators/sources?

**Comment by zx70** [comment]
It is not, but very close.
I picked the few fixes I saw around, including a pending commit proposal to your local copy of the M2000 sources, and grouped them together (including my original work which I had used long ago to build the 32bit version you already have).
I built the executables (which I'm proposing here) and requested @CodeAsm, to pull the sources, since he looked active on them.

**Comment by zx70** [comment]
Thankyou everybody for the feedback.  I'm a bit ashamed I didn't understand that 'for' loop myself!   Oddly the emulator worked also with that bug  :/

**Pull request closed without merging**
