### PR TITLE
Windows x64 Bin

### PR DESCRIPTION
**Pull request by zx70**

### CODE REVIEW

**Comment by zx70** [comment]
Thankyou

**Comment by dionoid** [comment]
Hi Stefano, for my information: did you make any new changes in the M2000 code for this Win64 version?
Also, what Makefile did you use? It looks like this version depends on libs like ligjpeg, libwebp, libwinpthread and libpng.

**Comment by zx70** [comment]
No extra changes.  Do you mean that the binary is not complete because of the lack of some dll file?

**Comment by dionoid** [comment]
No, all binaries are there, but I'm trying to get the same output files when building. I noticed that the Windows 32-bit version was built/linked with libraries "**-lallegro -lallegro_primitives -lallegro_image -lallegro_audio**", while the Windows 64-bit version was built/linked with libs "**-lallegro-static -lallegro_primitives-static -lallegro_image-static -lallegro_font-static -lallegro_audio-static -lallegro_dialog-static -lwinmm -lshlwapi -lpsapi -lopengl32 -lgdi32 -lsupc++ -lole32 -lpng -ljpeg -ldsound -lwebp**"

Was this done to increase performance of m2000.exe? Getting all the correct libs in place might be a hassle. 

Note that the Windows 64-bit version compiles fine with only using "**-lallegro -lallegro_primitives -lallegro_image -lallegro_audio**" (using static allegro libs)

**Comment by zx70** [comment]
No, I grabbed as much static stuff I could.  If you did better it's fine

**Comment by dionoid** [comment]
Thanks. I'll pick it up from there!

**Comment by zx70** [comment]
I suggest to test the resulting program on a  different computer with no mingw environment

**Pull request merged**
